name: CI

on:
  push:
    branches: [ main, hello-world-processor ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
        check-latest: true

    - name: Verify dependencies
      run: go mod tidy && go mod verify

    - name: Lint
      run: |
        go vet ./...
        go fmt ./...

    - name: Test
      run: go test -race -v ./...

    - name: Vulnerability check
      run: go run golang.org/x/vuln/cmd/govulncheck@latest ./...
      
    - name: Build
      run: go build -v ./cmd/collector

  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build Docker image
      run: docker build -t nrdot-process-optimization:test -f build/Dockerfile .
